# Generated by Django 3.2.14 on 2022-10-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название десерта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Главное фото')),
                ('cooking_time', models.PositiveSmallIntegerField(verbose_name='Время готовки (в минутах)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('category', models.ManyToManyField(related_name='category', to='recipe.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_text', models.TextField(verbose_name='Рецепт')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('dessert', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe.dessert')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='users_photos/%Y/%m/%d', verbose_name='Фото профиля')),
                ('photo_base', models.FilePathField(blank=True, path='users_photos/userphoto.jpg')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_change_pass', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения пароля')),
                ('sex', models.BooleanField(blank=True, choices=[(1, 'Женский'), (0, 'Мужской')], null=True, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dessert',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='recipe.profile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Оставьте комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dessert', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dessert_comment', to='recipe.dessert')),
                ('profile', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comment', to='recipe.profile')),
            ],
        ),
    ]
